base_model: ./models/llama3_it_with_padding_token
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: RLHFlow/Llama3-SFT-RAFT-Ultrafeedback-iter1
    conversation: llama-3
    type: sharegpt.load_ultrachat
    split: "train"
    train_on_split: "train"

warmup_steps: 40
val_set_size: 0.0
output_dir: ./models/llama3-8b-it_bs128_lr5e-7
#wandb_project: raft_train
#wandb_entity: raft
wandb_watch:
wandb_name: "llama-8b-it_bs64_lr5e-7"
wandb_log_model:

train_on_inputs: false

save_safetensors: true
#noisy_embedding_alpha: 10.0 # default for sharegpt type
dataset_prepared_path: ~/data/preference-models/last_run_prepared


dataset_processes: 48
#torch_compile: true
sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

trust_remote_code: True
adapter:
lora_model_dir:
#lora_r: 32
#lora_alpha: 16
#lora_dropout: 0.05
#lora_target_linear: true
#lora_fan_in_fan_out:




gradient_checkpointing: True

#warmup_ratio: 0.1
gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
#max_steps: 10
#optimizer: adamw_torch_fused
optimizer: paged_adamw_32bit
#lr_scheduler: constant_with_warmup
lr_scheduler: cosine
learning_rate: 5.0e-6

weight_decay: 0.0
max_grad_norm: 1.0


group_by_length: false
bf16: auto
fp16: false
tf32: true

early_stopping_patience:
local_rank:
logging_steps: 2
xformers_attention:
flash_attention: true


eval_steps:
eval_table_size:
eval_table_max_new_tokens:
#save_steps: 100
save_strategy: "epoch"
save_total_limit: 1
#save_safetensors: false
debug:


ddp: #true
deepspeed: #deepspeed/zero1.json # multi-gpu only

fsdp:
fsdp_config:
special_tokens:

